# Generated by Django 5.2.17 on 2026-10-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=16)),
                ('environment', models.CharField(default='production', max_length=32)),
                ('release', models.CharField(blank=True, max_length=64)),
                ('conversation_id', models.CharField(blank=True, max_length=64)),
                ('agent_name', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('input_summary', models.TextField(blank=True)),
                ('output_summary', models.TextField(blank=True)),
                ('total_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_output_tokens', models.PositiveIntegerField(default=0)),
                ('total_cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('error_span_count', models.PositiveIntegerField(default=0)),
                ('leaf_error_count', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='traces.project')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span_id', models.CharField(max_length=16)),
                ('parent_span_id', models.CharField(blank=True, max_length=16, null=True)),
                ('op', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=16)),
                ('start_ms', models.PositiveIntegerField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('agent_name', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('tool_name', models.CharField(blank=True, max_length=120)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('input_text', models.TextField(blank=True)),
                ('output_text', models.TextField(blank=True)),
                ('error_type', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('attributes', models.JSONField(default=dict)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='traces.trace')),
            ],
            options={
                'ordering': ['start_ms', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='traces.project')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='uniq_agent_name_per_project')],
            },
        ),
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=['status'], name='traces_trac_status_c756b1_idx'),
        ),
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=['conversation_id'], name='traces_trac_convers_e5745a_idx'),
        ),
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=['-started_at'], name='traces_trac_started_4e8ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='span',
            index=models.Index(fields=['trace', 'status'], name='traces_span_trace_i_bd01ef_idx'),
        ),
        migrations.AddIndex(
            model_name='span',
            index=models.Index(fields=['model'], name='traces_span_model_1cc96d_idx'),
        ),
        migrations.AddConstraint(
            model_name='span',
            constraint=models.UniqueConstraint(fields=('trace', 'span_id'), name='uniq_span_per_trace'),
        ),
    ]
